### ISSUE TITLE
Slight teleport timing adjustment

### ISSUE THREAD

**Issue by HyperSoop** [Stellarica/Stellarica-Server#20]
When piloting a ship, the blocks of it and the player are teleported at the same time on the server, but on the client the player is teleported instantly and chunks need a bit of time to update to adjust for the moved ship. Therefore, the player can see the ship's blocks lagging behind a little bit. This issue will be able to be be improved with the release of 1.19.4, but it would cause FPS lag on the client. One other way to fix this would be to add a very small artificial delay to entity teleportation on the client, in which we'd wanna accept false negatives to prevent false positives, but which would still really help movement.

**Comment by HyperSoop** [comment]
I feel like it could be 1/60th of a second.

**Comment by trainb0y** [comment]
There are better ways to smooth out teleporting than an artificial delay, I think. Either way I'll add a similar issue to the todo.

**Comment by HyperSoop** [comment]
> There are better ways to smooth out teleporting than an artificial delay, I think. Either way I'll add a similar issue to the todo.

Its different than smoothing out teleporting, it's about making teleporting smoother visually and not physically

**Comment by HyperSoop** [comment]
[video](https://files.catbox.moe/xjgwjy.mp4) here

it'll be here just in case, this flickering is the thing that needs to be smoothed out somehow
