### ISSUE TITLE
idea/todo ship armor /shields

### ISSUE THREAD

**Issue by HyperSoop** [Stellarica/Stellarica-Server#6]
_I'll be leaving my ideas on the repo here so they can be properly put into the project and organized_

Ship armor that in a radius of few blocks from itself takes all damage to blocks in this area from explosions and other ship weapons on itself, having durability and breaking after a few hits.

**Comment by HyperSoop** [comment]
armor blocks could be based off vanilla respawn anchors, they have a charge display which is exactly what we need to indicate armor block durability

**Comment by HyperSoop** [comment]
Armor also should not absorb *all* damage, top efficency should be around 95%. There could be armor that absorbs less damage, but has a higher radius of effect (like a 40% reduction of damage to a 5 block radius around)

**Comment by HyperSoop** [comment]
Basically, when a block gets broken and there is an armor block within acceptable radius of it the block doesn't break and the armor gets damaged by a value calculated from the block's blast resistance.

The armor should slowly regenerate durability on its own (to lessen the hassle for the player in case they aren't in battle for a long time) but it would also be able to be manually repaired with its corresponding material.

**Comment by HyperSoop** [comment]
> Armor also should not absorb _all_ damage, top efficency should be around 95%. There could be armor that absorbs less damage, but has a higher radius of effect (like a 40% reduction of damage to a 5 block radius around)

How specifically this should work is by either:  

basically multiplying the effective blast resistance of blocks in the radius by 1/(efficency).
or  
taking a random roll for each block that's supposed to be broken by the explosion and if it lands on the efficency percentage making it not break.
In either case the shield/armor loses durability for each block it protects from being broken.

Those 2 approaches could be separated into different shield/armor types - the latter is easier to obtain, has a bit higher efficency, but makes it easier to deal damage to infrastructure inside the ship or base, with the first being more expensive, but being able to prevent damage entirely, and if not, limit it to the surface defence layers of the ship/base.

**Comment by HyperSoop** [comment]
[Saw this.](https://discord.com/channels/1038493335679156425/1039962486687928380/1039962486687928380) I think it would be a good idea to make a sort of mixed thing for shields, where shields also provide a few fully negated hits in case you don't wanna put armor everywhere on your ship.

**Comment by HyperSoop** [comment]
Do we really need type-2 armor? Removing it out of the equation would ease the effort of balancing™. For shields it's especially relevant, type 2 shields would likely be considered useless and messy.

**Comment by HyperSoop** [comment]
> Do we really need type-2 armor? Removing it out of the equation would ease the effort of balancing™. For shields it's especially relevant, type 2 shields would likely be considered useless and messy.

Seems like i've convinced myself we don't really need it. That'll speed up my balancing™ process heavily.  
Why? Well T2 armor would be...  
- unable to prevent damage to inside things, and since it'd be used by newbies with small ships, it'd be useless to its target demographic (due to it not having otherwise thick walls)
- messy to deal with due to possible invisible damage inside your walls happening   

Shields:  
- even more messy (AAAAA level messy)  

That's why we're sticking to T1 (increased blast resistance) armor, providing progression through durability increases. For now at least

**Comment by HyperSoop** [comment]
Now, for mixed shields. The shield progression would be to build up more of its multiblock for more radius and to pump more energy into it for more defence. The way the energy part would work is that when a shield'd be above 50% in charge, it'd recieve a boost to its efficency (only works with multiblock shields), the more energy, the bigger, in an exponential way. That is, if 50% charge is 30% protection, 60% charge would be 35%, 70%-45% 80%-60% 90%- 80%, 100%-100%, so the more energy you have to pump into the shield, the more protection you get on average if you're being constantly attacked.  
That is, it both follows the premise of making the first few hits on your ship easily resistable, AND the idea of letting ground bases be very hard to raid! (since such bases would be self-sustainable in terms of energy, and be able to produce much more than size-limited ships. We should also add thermal energy generators to reinforce this)

For armor, it's easy. They take priority below shields in reflecting damage, and their progression consists of using different crafting recipes to get armor of different durability (with each type reflecting pretty much all damage no matter the durability, and breaking when the durability is done)

**Comment by trainb0y** [comment]
Closing for organizational purposes.
